// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEt-w72ICDa3tZa07A24KigrVrWjmB84s',
    appId: '1:233951733714:web:82c3337c4b1469260d8a0b',
    messagingSenderId: '233951733714',
    projectId: 'medicare-e5834',
    authDomain: 'medicare-e5834.firebaseapp.com',
    storageBucket: 'medicare-e5834.firebasestorage.app',
    measurementId: 'G-HYGJYJJQTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-zwuqkzOs7PAQJNpU8048RAAMaTyEcXY',
    appId: '1:233951733714:android:7e437ce77101d3f30d8a0b',
    messagingSenderId: '233951733714',
    projectId: 'medicare-e5834',
    storageBucket: 'medicare-e5834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBStmM_ZEAukh4imnJLd440QY2UvGQPDbM',
    appId: '1:233951733714:ios:ef044d9285c3172f0d8a0b',
    messagingSenderId: '233951733714',
    projectId: 'medicare-e5834',
    storageBucket: 'medicare-e5834.firebasestorage.app',
    iosBundleId: 'com.example.medicareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBStmM_ZEAukh4imnJLd440QY2UvGQPDbM',
    appId: '1:233951733714:ios:ef044d9285c3172f0d8a0b',
    messagingSenderId: '233951733714',
    projectId: 'medicare-e5834',
    storageBucket: 'medicare-e5834.firebasestorage.app',
    iosBundleId: 'com.example.medicareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEt-w72ICDa3tZa07A24KigrVrWjmB84s',
    appId: '1:233951733714:web:8ee755b085d74dc80d8a0b',
    messagingSenderId: '233951733714',
    projectId: 'medicare-e5834',
    authDomain: 'medicare-e5834.firebaseapp.com',
    storageBucket: 'medicare-e5834.firebasestorage.app',
    measurementId: 'G-3P9ZMCVC2J',
  );

}